@echo off
echo start processing OP310...
python -m extract_files "OP310.json"
echo start processing OP320...
python -m extract_files "OP320.json"
echo start processing OP360...
python -m extract_files "OP360.json"
pause